# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.

  # Forward local host port 8090 to zeppelin port 8090
  # comment out the following line out to use a fixed IP
  config.vm.network "forwarded_port", guest: 8090, host: 8090

  # Uncomment to create a private network, which allows access to the machine
  # using a specific IP.  Port forwarding not required in this case
  #config.vm.network "private_network", ip: "192.168.51.52"


 config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
 end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible-roles.yml"
  end

  config.vm.provision "shell", path: "show-instructions.sh", run: "always"

end
