# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG repo
ARG version

FROM ${repo}/zeppelin-interpreter-base:${version}
MAINTAINER Apache Software Foundation <dev@zeppelin.apache.org>

# Install ipython so that we can irkernel
RUN wget https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p $HOME/miniconda && \
    rm miniconda.sh && \
    export PATH=$HOME/miniconda/bin:$PATH && \
    conda config --set always_yes yes --set changeps1 no && \
    conda update -q conda && \
    conda info -a && \
    conda config --add channels conda-forge && \
    pip install -q grpcio==1.19.0 protobuf==3.10.0 ipython==7.8.0 matplotlib==3.0.3 ipykernel==5.1.2 jupyter_client==5.3.4

# Install necessary r packages
RUN export PATH=$HOME/miniconda/bin:$PATH && \
    export DEBIAN_FRONTEND=noninteractive && \
    set -ev && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && \
    add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' && \
    apt-get update && \
    apt-get install -y r-base && \
    R -e "install.packages('evaluate', repos = 'https://cloud.r-project.org')"  && \
    R -e "install.packages('base64enc', repos = 'https://cloud.r-project.org')"  && \
    R -e "install.packages('knitr', repos = 'https://cloud.r-project.org')"  && \
    R -e "install.packages('ggplot2', repos = 'https://cloud.r-project.org')"  && \
    R -e "install.packages('IRkernel', repos = 'https://cloud.r-project.org');IRkernel::installspec()"  && \
    R -e "install.packages('shiny', repos = 'https://cloud.r-project.org')" && \
    R -e "install.packages('googleVis', repos = 'https://cloud.r-project.org')"

COPY zeppelin-${VERSION}/interpreter/r ${Z_HOME}/interpreter/r
