# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG repo
ARG version

FROM ${repo}/zeppelin-base:${version}
MAINTAINER Apache Software Foundation <dev@zeppelin.apache.org>

ARG version

COPY zeppelin-${version}/bin ${Z_HOME}/bin
COPY zeppelin-${version}/interpreter/zeppelin-interpreter-shaded-${version}.jar ${Z_HOME}/interpreter/zeppelin-interpreter-shaded-${version}.jar
COPY log4j.properties ${Z_HOME}/conf/
COPY log4j_yarn_cluster.properties ${Z_HOME}/conf/
