##
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

FROM openjdk:11

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y wget apt-transport-https curl gnupg
#    rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - && \
    echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-7.x.list

RUN apt-get update && \
    apt-get install -y elasticsearch=7.10.1
#    rm -rf /var/lib/apt/lists/*

EXPOSE 9200 9300

ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

RUN chown -R elasticsearch:elasticsearch /var/lib/elasticsearch && \
    chown -R elasticsearch:elasticsearch /etc/elasticsearch

USER elasticsearch

CMD /usr/share/elasticsearch/bin/elasticsearch \
    -Enetwork.host=0.0.0.0 \
    -Ediscovery.type=single-node \
    -Ecluster.name=elasticsearch \
    -Ehttp.port=9200 \
    -Etransport.port=9300 \
    -Expack.security.enabled=false \
    -Expack.security.transport.ssl.enabled=false \
    -Expack.security.http.ssl.enabled=false
