{
 "title": "Zeppelin",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_max_bytes, namespace)"
    }
   },
   {
    "name": "mem_pool_heap_id",
    "label": "Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"heap\"}, id)"
    }
   },
   {
    "name": "mem_pool_nonheap_id",
    "label": "Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"nonheap\"}, id)"
    }
   },
   {
    "name": "methods",
    "query": {
     "query": "label_values(jetty_server_requests_seconds_count{namespace=\"$namespace\"}, method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Pools Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\"}) / sum(jvm_memory_max_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "process_files_open_files{namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cache Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(zeppelin_note_cache_hit_total{namespace=\"$namespace\"}) / (sum(zeppelin_note_cache_hit_total{namespace=\"$namespace\"}) + sum(zeppelin_note_cache_miss_total{namespace=\"$namespace\"}))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(zeppelin_note_cache_miss_total{namespace=\"$namespace\"}) / (sum(zeppelin_note_cache_hit_total{namespace=\"$namespace\"}) + sum(zeppelin_note_cache_miss_total{namespace=\"$namespace\"}))",
     "legendFormat": "Miss"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "used {{ pod }}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "committed {{ pod }}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "max {{ pod }}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"heap\"}) by (pod)",
     "legendFormat": "used {{ pod }}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", area=\"heap\"}) by (pod)",
     "legendFormat": "committed {{ pod }}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", area=\"heap\"}) by (pod)",
     "legendFormat": "max {{ pod }}"
    }
   ]
  },
  { "title": "Heap Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$mem_pool_heap_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "repeat": "mem_pool_heap_id",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", id=\"$mem_pool_heap_id\"}",
     "legendFormat": "max {{ pod }}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", id=\"$mem_pool_heap_id\"}",
     "legendFormat": "used {{ pod }}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", id=\"$mem_pool_heap_id\"}",
     "legendFormat": "comitted {{ pod }}"
    }
   ]
  },
  { "title": "Non-Heap Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$mem_pool_nonheap_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "repeat": "mem_pool_nonheap_id",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", id=\"$mem_pool_nonheap_id\"}",
     "legendFormat": "max {{ pod }}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", id=\"$mem_pool_nonheap_id\"}",
     "legendFormat": "used {{ pod }}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", id=\"$mem_pool_nonheap_id\"}",
     "legendFormat": "comitted {{ pod }}"
    }
   ]
  },
  { "title": "Jetty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jetty_connections_max_connections{namespace=\"$namespace\"}",
     "legendFormat": "Connection Pool Size"
    },
    {
     "expr": "jetty_connections_current_connections{namespace=\"$namespace\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(jetty_threads_current{namespace=\"$namespace\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(jetty_threads_busy{namespace=\"$namespace\"})",
     "legendFormat": "Busy"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(jetty_server_requests_seconds_count{namespace=\"$namespace\"}[5m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Request Average Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jetty_server_requests_seconds_sum{namespace=\"$namespace\"} / jetty_server_requests_seconds_count{namespace=\"$namespace\"}) by (method,status)",
     "legendFormat": "{{ method }}: {{ status }}"
    }
   ]
  },
  {
   "title": "$methods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "repeat": "methods",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(jetty_server_requests_seconds_count{namespace=\"$namespace\", method=\"$methods\"}[5m])) by (method)",
     "legendFormat": "{{ method }} Count"
    }
   ]
  }
 ]
}