# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python_interpreter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='python_interpreter.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18python_interpreter.proto\"\x1b\n\x0b\x43odeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\"\n\x10InterpetedResult\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x11PythonInterpreter\x12-\n\nInterprete\x12\x0c.CodeRequest\x1a\x11.InterpetedResultb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CODEREQUEST = _descriptor.Descriptor(
  name='CodeRequest',
  full_name='CodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='CodeRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_INTERPETEDRESULT = _descriptor.Descriptor(
  name='InterpetedResult',
  full_name='InterpetedResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='InterpetedResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['CodeRequest'] = _CODEREQUEST
DESCRIPTOR.message_types_by_name['InterpetedResult'] = _INTERPETEDRESULT

CodeRequest = _reflection.GeneratedProtocolMessageType('CodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _CODEREQUEST,
  __module__ = 'python_interpreter_pb2'
  # @@protoc_insertion_point(class_scope:CodeRequest)
  ))
_sym_db.RegisterMessage(CodeRequest)

InterpetedResult = _reflection.GeneratedProtocolMessageType('InterpetedResult', (_message.Message,), dict(
  DESCRIPTOR = _INTERPETEDRESULT,
  __module__ = 'python_interpreter_pb2'
  # @@protoc_insertion_point(class_scope:InterpetedResult)
  ))
_sym_db.RegisterMessage(InterpetedResult)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class PythonInterpreterStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Interprete = channel.unary_unary(
        '/PythonInterpreter/Interprete',
        request_serializer=CodeRequest.SerializeToString,
        response_deserializer=InterpetedResult.FromString,
        )


class PythonInterpreterServicer(object):

  def Interprete(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PythonInterpreterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Interprete': grpc.unary_unary_rpc_method_handler(
          servicer.Interprete,
          request_deserializer=CodeRequest.FromString,
          response_serializer=InterpetedResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PythonInterpreter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaPythonInterpreterServicer(object):
  def Interprete(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaPythonInterpreterStub(object):
  def Interprete(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Interprete.future = None


def beta_create_PythonInterpreter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('PythonInterpreter', 'Interprete'): CodeRequest.FromString,
  }
  response_serializers = {
    ('PythonInterpreter', 'Interprete'): InterpetedResult.SerializeToString,
  }
  method_implementations = {
    ('PythonInterpreter', 'Interprete'): face_utilities.unary_unary_inline(servicer.Interprete),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_PythonInterpreter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('PythonInterpreter', 'Interprete'): CodeRequest.SerializeToString,
  }
  response_deserializers = {
    ('PythonInterpreter', 'Interprete'): InterpetedResult.FromString,
  }
  cardinalities = {
    'Interprete': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'PythonInterpreter', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
