name: Zeppelin CI

on: [push, pull_request]

jobs:
  # Test License compliance using RAT tool
  license-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean -Prat -B org.apache.rat:apache-rat-plugin:check
